name: fall_detection_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  firebase_core: ^2.25.0
  cloud_firestore: ^4.15.0
  url_launcher: ^6.2.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/ 


flutter_icons:
  android: true
  ios: true
  image_path: assets/icons/app_icon.png

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/image1.png

  android_12:
    image: assets/images/image1.png
    icon_background_color: "#FFFFFF"
    color: "#FFFFFF"

  android: true
  ios: true
